config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  resources :projects
  devise_for :users, controllers: { invitations: 'users/invitations' }
  devise_scope :user do
    authenticated :user, ->(user) { user.has_role?(:superadmin) } do
      # root to: 'some_controller#index', as: :superadmin_root
      mount Sidekiq::Web => '/sidekiq'
    end
  end
  resources :users, except: %i[show]
  resources :evaluation_criteria, except: %i[show]

  root to: 'landing#index'
  get 'landing', to: 'landing#index'
  get 'configuration', to: 'evaluation_criteria#index', as: :configuration
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  invitation_token       :string
#  invitation_created_at  :datetime
#  invitation_sent_at     :datetime
#  invitation_accepted_at :datetime
#  invitation_limit       :integer
#  invited_by_type        :string
#  invited_by_id          :bigint
#  invitations_count      :integer          default(0)
#  name                   :string
#  phone                  :string
#  position               :string
#

#
# A person's access to the platform. Users have Roles which give context
# for what they can do and access
#
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/users/invitations_controller.rb
# frozen_string_literal: true

module Users
  class InvitationsController < Devise::InvitationsController
    def new
      authorize resource_class, :create?
      super
    end

    private

    def invite_resource(&block)
      authorize resource_class, :create?
      # We will override this method to also assign roles
      resource_class.invite!(invite_params, current_inviter, &block)
    end

    def after_invite_path_for(_resource)
      users_path
    end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :set_user, only: %i[edit update destroy]

  def index
    authorize User
    @deco_users = policy_scope(User.all).decorate
  end

  def new
    authorize User
    @user = User.new
  end

  def edit
    authorize @user
  end

  def update
    authorize @user
    return on_update_succeeded if @user.update(user_params)

    flash[:alert] = @project.errors.full_messages
    render :edit
  end

  def destroy
    authorize @user
    return on_destroy_succeeded if @user.destroy

    redirect_to users_path, alert: @project.errors.full_messages
  end

  private

  def on_destroy_succeeded
    redirect_to users_path,
                notice: t(
                  'controllers.shared_messages.successfully_deleted',
                  resource_name: t(@user.model_name)
                )
  end

  def on_update_succeeded
    redirect_to users_path,
                notice: t(
                  'controllers.shared_messages.successfully_saved',
                  resource_name: t(@user.model_name)
                )
  end

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :name, :phone, :position)
  end
end

app/views/users/_form.html.erb
<div class="container">
  <%= form_for @user do |f| %>
    <%= render 'components/section_header', title: "#{(t action_name, scope: 'controller_actions').titleize} #{User.model_name.human}" do %>
      <div class="actions">
        <%= render 'components/forms/submit_button_main', f:f %>
      </div>
    <% end %>
    <div class="card">
      <div class="card-body">
        <div class="form-group">
          <%= f.label :email %>
          <%= f.text_field :email, class: "form-control", type: 'email' %>
        </div>
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :phone %>
          <%= f.text_field :phone, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :position %>
          <%= f.text_field :position, class: "form-control" %>
        </div>
        <div class="form-group">
          <label for="roles">Roles</label>
          <%= select_tag 'roles[0]', options_for_select(["Member", "Admin"]),
                                     include_hidden: false, selected: "member",
                                     multiple: true,
                                     class:"form-control select--main auto-select2 select-select2",
                                     required: true %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<%= render 'form', user: @user %>

app/views/users/index.html.erb
<%= render 'layouts/flash_messages' %>
<div class="container">
  <%= render 'components/section_header', title: User.model_name.human(count: 2) do %>
    <div class="actions">
      <%= link_to 'Add User', new_user_invitation_path, class: 'btn btn-secondary sticky-button btn-lg py-3' %>
    </div>
  <% end %>
  <div class="card">
    <div class="card-body table-responsive">
      <table class="table table-striped table-borderless table-light rspec_users_table">
        <thead>
          <tr>
            <th><%= t User.human_attribute_name :name  %></th>
            <th><%= t User.human_attribute_name :email  %></th>
            <th><%= t User.human_attribute_name :phone  %></th>
            <th><%= t User.human_attribute_name :position  %></th>
            <th><%= t User.human_attribute_name :invitation_sent_at  %></th>
            <th><%= t User.human_attribute_name :invitation_accepted_at  %></th>
            <th><%= t User.human_attribute_name :invited_by  %></th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @deco_users.each do |deco_user| %>
            <tr>
              <td><%= deco_user.html_attr(:name) %></td>
              <td><%= deco_user.email %></td>
              <td><%= deco_user.html_attr(:phone) %></td>
              <td><%= deco_user.html_attr(:position) %></td>
              <td><%= deco_user.html_attr(:invitation_sent_at) %></td>
              <td><%= deco_user.html_attr(:invitation_accepted_at) %></td>
              <td><%= deco_user.html_attr(:invited_by) %></td>
              <td>
                <div class="dropdown">
                  <button class="btn btn-outline-primary dropdown-toggle btn-sm" type="button" id="<%= "user_#{deco_user.id}_options" %>" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <%= t 'Actions' %>
                  </button>
                  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <%= link_to t('controller_actions.edit').titleize, edit_user_path(deco_user), class: 'dropdown-item' %>
                    <%= link_to t('controller_actions.delete').titleize, user_path(deco_user), method: :delete,
                                          data: { confirm: t('confirm_delete_resource') }, class: 'dropdown-item'  %>
                  </div>
                </div>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<%= render 'form', user: @user %>