config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  resources :projects
  devise_for :users, controllers: { invitations: 'users/invitations' }
  devise_scope :user do
    authenticated :user, ->(user) { user.has_role?(:superadmin) } do
      # root to: 'some_controller#index', as: :superadmin_root
      mount Sidekiq::Web => '/sidekiq'
    end
  end
  resources :users, except: %i[show]
  resources :evaluation_criteria, except: %i[show]

  root to: 'landing#index'
  get 'landing', to: 'landing#index'
  get 'configuration', to: 'evaluation_criteria#index', as: :configuration
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  invitation_token       :string
#  invitation_created_at  :datetime
#  invitation_sent_at     :datetime
#  invitation_accepted_at :datetime
#  invitation_limit       :integer
#  invited_by_type        :string
#  invited_by_id          :bigint
#  invitations_count      :integer          default(0)
#  name                   :string
#  phone                  :string
#  position               :string
#

#
# A person's access to the platform. Users have Roles which give context
# for what they can do and access
#
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/users/invitations_controller.rb
# frozen_string_literal: true

module Users
  class InvitationsController < Devise::InvitationsController
    def new
      authorize resource_class, :create?
      super
    end

    private

    def invite_resource(&block)
      authorize resource_class, :create?
      # We will override this method to also assign roles
      resource_class.invite!(invite_params, current_inviter, &block)
    end

    def after_invite_path_for(_resource)
      users_path
    end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :set_user, only: %i[edit update destroy]

  def index
    authorize User
    @deco_users = policy_scope(User.all).decorate
  end

  def new
    authorize User
    @user = User.new
  end

  def edit
    authorize @user
  end

  def update
    authorize @user
    return on_update_succeeded if @user.update(user_params)

    flash[:alert] = @project.errors.full_messages
    render :edit
  end

  def destroy
    authorize @user
    return on_destroy_succeeded if @user.destroy

    redirect_to users_path, alert: @project.errors.full_messages
  end

  private

  def on_destroy_succeeded
    redirect_to users_path,
                notice: t(
                  'controllers.shared_messages.successfully_deleted',
                  resource_name: t(@user.model_name)
                )
  end

  def on_update_succeeded
    redirect_to users_path,
                notice: t(
                  'controllers.shared_messages.successfully_saved',
                  resource_name: t(@user.model_name)
                )
  end

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :name, :phone, :position)
  end
end

app/views/users/invitations/edit.html.erb
<h2><%= t 'devise.invitations.edit.header' %></h2>
<%= form_for resource, :as => resource_name, :url => invitation_path(resource_name), :html => { :method => :put } do |f| %>
  <%= render 'devise/shared/error_messages', resource: f.object %>
  <%= f.hidden_field :invitation_token, readonly: true %>
  <% if f.object.class.require_password_on_accepting %>
    <p><%= f.label :password %><br />
      <%= f.password_field :password %></p>
    <p><%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation %></p>
  <% end %>
  <p><%= f.submit t("devise.invitations.edit.submit_button") %></p>
<% end %>

app/views/users/invitations/new.html.erb
<div class="container">
  <%= form_for resource, :as => resource_name, :url => invitation_path(resource_name), :html => {:method => :post} do |f| %>
    <%= render 'components/section_header', title: t("devise.invitations.new.header") do %>
      <div class="actions">
        <%= f.submit t("devise.invitations.new.submit_button"), class: 'btn btn-secondary sticky-button btn-lg py-3' %>
      </div>
    <% end %>
    <div class="card">
      <div class="card-body">
        <%= render 'devise/shared/error_messages', resource: f.object %>
        <p>
          <div class="form-group">
            <%= f.label :email %>
            <%= f.text_field :email, type: 'email', class: "form-control" %>
            <small class="text-primary"><%= t 'features.invites.email_helper_text' %></small>
          </div>
          <div class="form-group">
            <h3>Roles</h3>
            <div class="row">
              <div class="col-sm-12 col-md-6">
                <label for="roles">Role</label>
                <%= select_tag 'roles[0][name]', options_for_select(["Member", "Admin"]),
                                     include_hidden: false, value: "Member",
                                     multiple: false,
                                     class:"form-control select--main auto-select2 select-select2"%>
              </div>
              <div class="col-sm-12 col-md-6">
                <label for="roles">Resource</label>
                <%= select_tag 'roles[0][resource_id]', options_for_select([["Some Startup", 1], ["Kleen NRG", 2]]),
                                     include_hidden: false, value: 2,
                                     multiple: false,
                                     class:"form-control select--main auto-select2 select-select2"%>
              </div>
            </div>
          </div>
        </p>
      </div>
    </div>
  <% end %>
</div>