config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  resources :projects
  devise_for :users, controllers: { invitations: 'users/invitations' }
  devise_scope :user do
    authenticated :user, ->(user) { user.has_role?(:superadmin) } do
      # root to: 'some_controller#index', as: :superadmin_root
      mount Sidekiq::Web => '/sidekiq'
    end
  end
  resources :users, except: %i[show]
  resources :evaluation_criteria, except: %i[show]

  root to: 'landing#index'
  get 'landing', to: 'landing#index'
  get 'configuration', to: 'evaluation_criteria#index', as: :configuration
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/views/layouts/_config_sidebar.html.erb
<div class="nav flex-column nav-pills ml-3" id="v-pills-tab" role="tablist" aria-orientation="vertical">
  <%= link_to EvaluationCriterium.model_name.human(count: 2), evaluation_criteria_path,
                    class:"nav-link text-nowrap", data: {
                      'path-matchers': ['.*evaluation_criteria.?']
                    } %>
  <a class="nav-link" id="v-pills-profile-tab" data-toggle="pill" href="navs.htm#v-pills-profile" role="tab" aria-controls="v-pills-profile" aria-selected="false">Profile</a>
  <a class="nav-link" id="v-pills-messages-tab" data-toggle="pill" href="navs.htm#v-pills-messages" role="tab" aria-controls="v-pills-messages" aria-selected="false">Messages</a>
  <a class="nav-link" id="v-pills-settings-tab" data-toggle="pill" href="navs.htm#v-pills-settings" role="tab" aria-controls="v-pills-settings" aria-selected="true">Settings</a>
</div>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |key, value| %>
  <% if value.class == Array %>
    <% value.each do |subvalue| %>
      <%= "#{key}: #{subvalue.to_s.squish}" %>
    <% end %>
  <% else %>
    <%= "#{key}: #{value.to_s.squish}" %>
  <% end %>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary mb-4 px-5 py-0">
  <div class="logo logo-white"></div>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarColor02">
    <ul class="navbar-nav ml-auto mr-5">
      <li class="nav-item">
        <%= link_to t('navigation.configuration'), configuration_path,
                    class:"nav-link", data: {
                      'path-matchers': ['.*configuration.?','.*evaluation_criteria.?']
                    } %>
      </li>
    </ul>
    <form class="form-inline">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-light my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Evaluarium</title>
    <meta charset="utf-8" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" lang="en" content="">
    <meta name="description" lang="es" content="">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <link rel="shortcut icon" type="image/x-icon" href="/favicon.ico">
    <%= csrf_meta_tags %>
    <%= stylesheet_pack_tag 'application' %>
    <%= javascript_pack_tag 'application'%>
    <%= yield :stylesheets %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navbar' %>
    </header>
    <main class="d-flex">
      <%= render 'layouts/config_sidebar' if @config_section %>
      <%= yield %>
    </main>
    <footer class="waves-footer-container">
      <div class="waves-footer-content"></div>
      <div class="waves-footer-background"></div>
    </footer>
    <%= yield :javascripts %>
    <% if Rails.env.production? %>
      <script type="text/javascript">
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
          (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
          m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
        ga('create', '' , 'auto');
      </script>
    <% end %>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Evaluarium</title>
    <meta charset="utf-8" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" lang="en" content="">
    <meta name="description" lang="es" content="">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <link rel="shortcut icon" type="image/x-icon" href="/favicon.ico">
    <%= csrf_meta_tags %>
    <%= stylesheet_pack_tag 'application' %>
    <%= yield :stylesheets %>
  </head>
  <body>
    <header class="waves-header-container">
      <div class="waves-header-content"></div>
      <div class="waves-header-background"></div>
    </header>
    <main>
      <%= yield %>
    </main>
    <footer class="waves-footer-container">
      <div class="waves-footer-content"></div>
      <div class="waves-footer-background"></div>
    </footer>
    <% if Rails.env.production? %>
      <script type="text/javascript">
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
          (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
          m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
        ga('create', '' , 'auto');
      </script>
    <% end %>
  </body>
</html>

app/views/layouts/landing.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Evaluarium</title>
    <meta charset="utf-8" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" lang="en" content="">
    <meta name="description" lang="es" content="">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <link rel="shortcut icon" type="image/x-icon" href="/favicon.ico">
    <%= csrf_meta_tags %>
    <%= stylesheet_pack_tag 'application' %>
    <%= javascript_pack_tag 'application'%>
    <%= yield :stylesheets %>
  </head>
  <body>
    <%= yield %>
    <%= yield :javascripts %>
    <% if Rails.env.production? %>
      <script type="text/javascript">
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
          (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
          m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
        ga('create', '' , 'auto');
      </script>
    <% end %>
  </body>
</html>